name: 'OWASP Check with maven'
description: 'Checks your JAVA project for vulnerabilities'
inputs:
  failBuildOnCVSS:
    default: '5'
    required: false
    description: Score on which the build should fail
  outputDirectory:
    default: './'
    required: false
    description: Output directory to store report
  format:
    default: 'HTML'
    required: false
    description: Format of the report (HTML, XML, CSV, JSON, JUNIT, SARIF, ALL)
  suppressionFile:
    required: false
    description: Path/URL to suppression file to exclude false positives in report.
  submodule:
    required: false
    description: Path to submodule in Maven Multi-Module Project.
    default: './'
  args:
    required: false
    description: Pass all other arguments to maven or the owasp maven plugin

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-DscanDirectory=${{ inputs.submodule }}'
    - '-DdataDirectory=/dependency-check/data'
    - '-DfailBuildOnCVSS=${{ inputs.failBuildOnCVSS }}'
    - '-Dodc.outputDirectory=/github/workspace/${{ inputs.outputDirectory }}'
    - '-Dformat=${{ inputs.format }}'
    - '-DautoUpdate=false'
    - '-DsuppressionFiles=${{ inputs.suppressionFile }}'
    - ${{ inputs.args }}